### PR TITLE
support chatml-function-calling via llama-cpp

### PR DESCRIPTION
**Pull request by dnakov**
- [x] support `chatml-function-calling` via llama-cpp

### CODE REVIEW

**Comment by trufae** [comment]
See the EPIC ticket :)

**Comment by dnakov** [comment]
sounds good, i'll split them up!

**Comment by trufae** [comment]
So it's ok to merge now?

**Comment by trufae** [comment]
I want to merge this https://github.com/radareorg/r2ai/pull/6 as it's actually fixing the behaviour of code colorization and ive tested it with several models. the code is still not fully cleaned but its much simpler and at least it works as expected.

is it ok for you for me to merge it?

**Comment by dnakov** [comment]
Yeah go ahead, I'll deal with any merge conflicts when this is ready

**Comment by dnakov** [comment]
ok this works now, merged with your changes. Not getting any good results with mistral, but that's more of a model problem. Hopefully functionary will be a lot better

**Comment by trufae** [comment]
Ready to merge to start experimenting with it? I think enabling vectordb is important for the auto mode, as well as extending the doc/data stuff to give more contextual hints about how to achieve things and which commands use

**Comment by trufae** [comment]
uh "This branch cannot be rebased due to conflicts"

**Comment by trufae** [comment]
conflicts are too large to be resolved via github, please fix them and force push that.

i would recommend you for the next PR to use a separate branch (not named master) and use `git rebase` instead of `git merge`

Screenshot 2024-02-28 at 23 49 33

**Comment by trufae** [comment]
Also, note that commit messages must be capitalized, and i would recommend you to squash the commits

**Comment by dnakov** [comment]
ok should be good now

**Comment by dnakov** [comment]
> Ready to merge to start experimenting with it? I think enabling vectordb is important for the auto mode, as well as extending the doc/data stuff to give more contextual hints about how to achieve things and which commands use

yeah, to the extent of if you `-m TheBloke/Mistral-7B-Instruct-v0.2-GGUF` then prompt it with `' `, it'll use that model and it will call some function, but `chatml-function-calling` and the models are not "smart" and reliable enough to know when to stop calling functions and send a message. This can probably be offset a bit with different prompting + RAG, but my hope is for functionary.

How do you envision structuring the RAG data? What's the best "use case -> commands" documentation/reference that we can shove into the vectordb? If we just put the r2 docs in there, i don't think we'd get the any good results for high level queries like "solve this crackme" or "what's the password"

**Comment by dnakov** [comment]
Yeah ive gotten it to work only like once by luck. I'll add some debugging.

About the vectors, yeah, I know how RAG works, I mean what text are you thinking of putting in there, do you have examples?

**Pull request merged**
